"""add madhab and location_country to users

Revision ID: 53da05c68091
Revises: bce5e52fb1d4
Create Date: 2026-06-15 00:12:49.806022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53da05c68091'
down_revision: Union[str, Sequence[str], None] = 'bce5e52fb1d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location_country', sa.String(length=2), nullable=True))
    op.add_column('users', sa.Column('madhab', sa.String(length=10), server_default='shafi', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'madhab')
    op.drop_column('users', 'location_country')
    # ### end Alembic commands ###
