"""add calculation_method to users

Revision ID: bce5e52fb1d4
Revises: 10f23da3bba8
Create Date: 2026-06-13 23:22:33.403280

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bce5e52fb1d4'
down_revision: Union[str, Sequence[str], None] = '10f23da3bba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('calculation_method', sa.Integer(), server_default='3', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'calculation_method')
    # ### end Alembic commands ###
